version: '3'

services:
  web:
    container_name: stands
    image: ghcr.io/vatsim-scandinavia/stands:latest
    ports:
        - 8080:80
        - 8443:443
    extra_hosts:
        - "host.docker.internal:host-gateway"
    #environment:
    #  - APP_TRACKING_SCRIPT="<script>console.log('Insert your tracking script here or remove this variable alltogether.')</script>"
    #volumes:
    #  - ./:/app/